#ifndef ESTC_PROJECT_CONFIG_H
#define ESTC_PROJECT_CONFIG_H

#ifndef LOGGER_ENABLE
#define LOGGER_ENABLE 1
#endif

#ifndef USB_ENABLE
#define USB_ENABLE 1
#endif

#ifndef MEMORY_MAKE_RESET
#define MEMORY_MAKE_RESET 0
#endif

#endif //ESTC_PROJECT_CONFIG_H
